swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /account/{userId}:
    get:
      tags:
        - Account Module
      summary: Get User Accounts
      description: API to fetch user accounts by userId
      parameters:
        - name: userId
          in: path
          description: User ID
          required: true
          type: string
      security:
        - Bearer: []
      responses:
        '200':
          description: User accounts retrieved successfully
          schema:
            $ref: '#/definitions/AccountApiResponse'
        '401':
          description: Unauthorized
        '404':
          description: Account Not Found
        '500':
          description: Internal Server Error
  /transaction/{accountId}:
    get:
      tags:
        - Transaction Module
      summary: Get Account Transactions
      description: API to fetch account transactions by transactionId
      parameters:
        - name: accountId
          in: path
          description: account ID
          required: true
          type: string
      security:
        - Bearer: []
      responses:
        '200':
          description: account transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionApiResponse'
        '401':
          description: Unauthorized
        '404':
          description: Account's transaction Not Found
        '500':
          description: Internal Server Error
  /transaction/{accountId}/{transactionId}/category:
    put:
      tags:
        - Transaction Module
      summary: Update Transaction's Category
      description: API to update transaction's category by transactionId
      parameters:
        - name: transactionId
          in: path
          description: transaction ID
          required: true
          type: string
        - name: body
          in: body
          description: Request body containing user input
          required: true
          schema:
            type: object
            properties:
              userInputField:
                type: string
      security:
        - Bearer: []
      responses:
        '200':
          description: transaction's category updated successfully
          schema:
            $ref: '#/definitions/TransactionApiResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Category's key Not Found
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Transaction Module
      summary: Delete Transaction's Category
      description: API to delete transaction's category by transactionId
      parameters:
        - name: transactionId
          in: path
          description: transaction ID
          required: true
          type: string
      security:
        - Bearer: []
      responses:
        '204':
          description: transaction's category deleted successfully
          schema:
            $ref: '#/definitions/TransactionApiResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Category's key Not Found
        '500':
          description: Internal Server Error
  /transaction/{accountId}/{transactionId}/note:
    post:
      tags:
        - Transaction Module
      summary: Add Transaction's Note
      description: API to add transaction's note by transactionId
      parameters:
        - name: transaction Id
          in: path
          description: transaction ID
          required: true
          type: string
        - name: body
          in: body
          description: Request body containing user input
          required: true
          schema:
            type: object
            properties:
              userInputField:
                type: string  
      security:
        - Bearer: []
      responses:
        '201':
          description: transaction's note added successfully
          schema:
            $ref: '#/definitions/TransactionApiResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Note's key Not Found
        '500':
          description: Internal Server Error
    put:
      tags:
        - Transaction Module
      summary: Update Transaction's Note
      description: API to update transaction's note by transactionId
      parameters:
        - name: transactionId
          in: path
          description: transaction ID
          required: true
          type: string
        - name: body
          in: body
          description: Request body containing user input
          required: true
          schema:
            type: object
            properties:
              userInputField:
                type: string
      security:
        - Bearer: []
      responses:
        '200':
          description: transaction's note updated successfully
          schema:
            $ref: '#/definitions/TransactionApiResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Note's key Not Found
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Transaction Module
      summary: Delete Transaction's Note
      description: API to delete transaction's note by transactionId
      parameters:
        - name: transactionId
          in: path
          description: transaction ID
          required: true
          type: string
      security:
        - Bearer: []
      responses:
        '204':
          description: transaction's note deleted successfully
          schema:
            $ref: '#/definitions/TransactionApiResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Note's key Not Found
        '500':
          description: Internal Server Error
  
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      UserName:
        type: string
        description: user userName 
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  AccountApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Account'
  TransactionApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction'
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  
  Account:
    properties:
      user:
        type: string 
        description: User's Id connected to that account
      accountName:
        type: string
        description: Account Name
      accountNumber:
        type: string
        description: Account Number
      balance:
        type: number  
        description: Balance of the account, in cents
      currency:
        type: string
        description: Account's currency
  Transaction:
    properties:
      account:
        type: string 
        description: Account's Id connected to transactions
      Date:
        type: string
        description: Transaction's date
      Description:
        type: string
        description: Transaction Description
      Transacation Type:
        type: string
        description: Transaction Type
      Category:
        type: string
        description: Transaction Category
      Note:
        type: string
        description: Transaction Note (Blank by default)
      Ammount:
        type: number  
        description: Ammount of the transaction, in cents
      Balance:
        type: number
        description: Balance of the account after the transaction, in cents
  Category:
    properties:
      transaction:
        type: string 
        description: Transaction's Id connected to category
      Category:
        type: string
        description: Transaction Category
  Note:
    properties:
      transaction:
        type: string 
        description: Transaction's Id connected to note
      Note:
        type: string
        description: Transaction Note (Blank by default)
